### ISSUE TITLE
Redirect to log-in page when accessing restricted content

### ISSUE THREAD

**Issue by g12-al** [g12-al/NVDSite#11]
Use decorator @login_required with optional argument login_url = 'ReferMe/login/'

**Comment by acg224** [comment]
urls.py 
(r'^accounts/login/$', 'django.contrib.auth.views.login'),

*accounts: can we make something like this to encompass both realtors and clients?*

// not sure if this belongs to detail or view

from django.contrib.auth.views import login

def account(again just to encompass both realtor and client)_login(request):
    if request.account_login.is_authenticated():
        return HttpResponseRedirect(...)
    else:
        return login(request)

**Comment by g12-al** [comment]
Fixed in Commit # 8330a0884e91cb45fab5ae55626081473ff54def
