### ISSUE TITLE
Allow users to edit their review

### ISSUE THREAD

**Issue by g12-al** [g12-al/NVDSite#4]
Current functionality only permits writing reviews

**Comment by acg224** [comment]
detail.html

<a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>

url.py
url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),

views.py
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


*skeleton for my reference

**Comment by g12-al** [comment]
Partially done -- current functionality prevents users from writing multiple reviews.
